name: acpv-net
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.*
  - torchvision=0.16.*
  - torchaudio=2.1.*
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - pillow
  - pyyaml
  - cython
  - ninja
  - packaging
  - tqdm
  - opencv
  - imagecodecs
  - pip:
      - yacs==0.1.8
      - omegaconf
      - einops
      - pytorch-lightning<2.0
      - pycocotools
      - shapely
      - descartes
      - multiprocess
      - timm
      - triton==2.1.0
      - fvcore
      - iopath
      - mmcv==1.7.2
      - taming-transformers-rom1504
