from yacs.config import CfgNode as CN

MODELS = CN()

MODELS.NAME = "HRNet48v2"
MODELS.DEVICE = "cuda"
MODELS.HEAD_SIZE  = [[2]]
MODELS.OUT_FEATURE_CHANNELS = 256

# loss type
MODELS.LOSS_WEIGHTS = CN(new_allowed=True)
MODELS.LOSS = CN()
MODELS.LOSS.MASK_LOSS_TYPE = "ce"          # "ce" or "weighted_ce"
MODELS.LOSS.MASK_AUX_LOSS_TYPE = "ce"      # "ce" or "weighted_ce"
MODELS.LOSS.W_BG = 1.0
MODELS.LOSS.W_OBJ = 1.0
MODELS.LOSS.PARCEL_LOSS_TYPE = "ce"
MODELS.LOSS.PARCEL_AUX_LOSS_TYPE = "ce"
MODELS.LOSS.PARCEL_W_BG = 1.0
MODELS.LOSS.PARCEL_W_OBJ = 1.0
MODELS.DUAL_SEG = False
MODELS.JOINT_LATENT = False
MODELS.EDGE_LATENT_CHANNELS = 3
MODELS.VERTEX_LATENT_CHANNELS = 3
MODELS.LOSS.LOSS_EDGE_LATENT = 1.0
MODELS.LOSS.LOSS_VERTEX_LATENT = 1.0

# VMamba parameters
MODELS.BACKBONE = CN()
MODELS.BACKBONE.OUT_INDICES = [0, 1, 2, 3]
MODELS.BACKBONE.PRETRAINED = "./pretrained/vssm_small_0229_ckpt_epoch_222.pth"
MODELS.BACKBONE.DIMS = 96
MODELS.BACKBONE.DEPTHS = [2, 2, 15, 2]
MODELS.BACKBONE.SSM_D_STATE = 1
MODELS.BACKBONE.SSM_DT_RANK = "auto"
MODELS.BACKBONE.SSM_RATIO = 2.0
MODELS.BACKBONE.SSM_CONV = 3
MODELS.BACKBONE.SSM_CONV_BIAS = False
MODELS.BACKBONE.FORWARD_TYPE = "v05_noz"
MODELS.BACKBONE.MLP_RATIO = 4.0
MODELS.BACKBONE.DOWNSAMPLE_VERSION = "v3"
MODELS.BACKBONE.PATCHEMBED_VERSION = "v2"
MODELS.BACKBONE.DROP_PATH_RATE = 0.3
MODELS.BACKBONE.NORM_LAYER = "ln2d"

# UPerHead parameters
MODELS.DECODE_HEAD = CN()
MODELS.DECODE_HEAD.IN_CHANNELS = [96, 192, 384, 768]
MODELS.DECODE_HEAD.IN_INDEX = [0, 1, 2, 3]
MODELS.DECODE_HEAD.POOL_SCALES = [1, 2, 3, 6]
MODELS.DECODE_HEAD.CHANNELS = 512
MODELS.DECODE_HEAD.DROPOUT_RATIO = 0.1
MODELS.DECODE_HEAD.NUM_CLASSES = 7
MODELS.DECODE_HEAD.ALIGN_CORNERS = False
MODELS.DECODE_HEAD.UPSAMPLE_METHOD = "deconv"

# FCNHead parameters
MODELS.AUX_HEAD = CN()
MODELS.AUX_HEAD.IN_CHANNELS = 384
MODELS.AUX_HEAD.IN_INDEX = 2
MODELS.AUX_HEAD.CHANNELS = 256
MODELS.AUX_HEAD.NUM_CONVS = 1
MODELS.AUX_HEAD.CONCAT_INPUT = False
MODELS.AUX_HEAD.DROPOUT_RATIO = 0.1
MODELS.AUX_HEAD.NUM_CLASSES = 7
MODELS.AUX_HEAD.ALIGN_CORNERS = False

MODELS.coarse_to_fine = False

# Denoising UNet parameters
MODELS.unet_config = CN()
MODELS.unet_config.target = None

MODELS.unet_config.params = CN()
MODELS.unet_config.params.image_size = 128
MODELS.unet_config.params.in_channels = 3
MODELS.unet_config.params.out_channels = 3
MODELS.unet_config.params.model_channels = 224
MODELS.unet_config.params.attention_resolutions = [8, 4, 2]
MODELS.unet_config.params.num_res_blocks = 2
MODELS.unet_config.params.channel_mult = [1, 2, 3, 4]
MODELS.unet_config.params.num_head_channels = 32
MODELS.unet_config.params.context_dim = None
MODELS.unet_config.params.use_spatial_transformer = False

MODELS.conditioning_key = None

